Cakes/urls.py
from django.urls import path, re_path
from . import views


app_name = 'Cakes'
urlpatterns = [
    path('', views.PedidoListView.as_view(), name='pedidos_list'),
    path("create/", views.PedidoCreateView.as_view(), name="pedidos_new"),
    re_path(r'^pedido/(?P<pk>\d+)/delete/$', views.PedidoDeleteView.as_view(), name='pedidos_delete'),
    re_path(r'^pedido/(?P<pk>\d+)/update/$', views.PedidoUpdateView.as_view(), name='pedidos_update'),
    re_path(r'^pedido/(?P<pk>\d+)/detail/$', views.PedidoDetailView.as_view(), name='pedidos_detail'),
]

Chepina/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path("admin/", admin.site.urls),
    path("cakes/", include('Cakes.urls') )
]

Cakes/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
import datetime
# Create your models here.

class Pedidos(models.Model):
    sabor_Choices = (('Chocolate', 'chocolate'),
                     ('Vainilla', 'vainilla'),
                     ('Confetti', 'confetti'),
                     )
    sabor = models.CharField(max_length=208,choices=sabor_Choices)
    persona = models.CharField(max_length=208)
    fecha_pedido = models.DateField(default=timezone.now)
    fecha_entrega = models.DateField(blank=False, null=False)
    direccion = models.CharField(max_length=200)
    direccion_URL = models.URLField(blank=True, null=True)
    detalles = models.TextField(blank=True, null=True)
    entre = models.BooleanField(default=False)
    
    def __str__(self):
        return self.persona

    def get_absolute_url(self):
        return reverse("Cakes:pedidos_list")
    
    def entregado(self):
       self.entregado = True

    def days(self):
        diff = abs((datetime.date.today()-self.fecha_entrega).days)
        if diff<=1:
            return 'table-danger'
        if diff==2:
            return 'table-warning'
        if diff>=3 and diff <= 5:
            return 'table-info'
            



## SI mi direccion de pedido ya paso hace 5 dias borrar de Entregados

Cakes/forms.py
from . import models
from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput

class Form(forms.ModelForm):
    
    class Meta():
        model = models.Pedidos
        fields = ('sabor', 'persona','fecha_entrega', 'direccion', 'direccion_URL', 'detalles',)

        widgets = {
            'fecha_entrega': DatePickerInput()
        } 
    

Cakes/views.py
from django.shortcuts import render
from django.views.generic import DetailView, DeleteView, CreateView, ListView, UpdateView
from . import forms
from . import models
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
# Create your views here.

class PedidoCreateView(CreateView):
    form_class = forms.Form
    model = models.Pedidos
    

class PedidoUpdateView(UpdateView):
    form_class = forms.Form
    model = models.Pedidos

class PedidoDeleteView(DeleteView):
    model=models.Pedidos
    success_url = reverse_lazy('Cakes:pedidos_list')

class PedidoDetailView(DetailView):
    model = models.Pedidos

class PedidoListView(ListView):
    model = models.Pedidos
    
    def get_queryset(self):
        return models.Pedidos.objects.filter(entre=False).order_by('fecha_entrega')

class EntregadosListView(ListView):
    model = models.Pedidos

    def get_queryset(self):
        return models.Pedidos.objects.filter(entre=True).order_by('-fecha_entrega')

        
    

templates/Cakes/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Chepina Pedidos</title>
    <!--Bootstrap 5-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!--Data Table-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-html5-2.3.3/b-print-2.3.3/date-1.2.0/fc-4.2.1/fh-3.3.1/r-2.4.0/sc-2.0.7/sb-1.4.0/datatables.min.css"/>
    <!--Data Picker-->
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>


  </head>
  <body>            
                <!--CAMBIAR EL COLOR DE LA BARRA-->
    <nav class="navbar navbar-expand-lg navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'Cakes:pedidos_list' %}">Chepina Pedidos</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'Cakes:pedidos_list' %}">Pedidos</a>
              <a class="nav-link " href="{% url 'Cakes:pedidos_new' %}">Nuevo Pedido</a>
            </div>
          </div>
        </div>
      </nav>
      
      {% block content %}
      {% endblock content %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-html5-2.3.3/b-print-2.3.3/date-1.2.0/fc-4.2.1/fh-3.3.1/r-2.4.0/sc-2.0.7/sb-1.4.0/datatables.min.js"></script>
    </script>

    </body>
</html>

templates/Cakes/pedidos_comfirm_delete.html
<!DOCTYPE html>
{% include 'Cakes/base.html' %}
{% block content %}
    <div class="container mt-5">
        <h1>Confirmar Eliminación</h1>
        <hr>    
        <p>Seguro que quieres eliminar este pedido?</p>
    <table class="table">
      <tr>
        <th>Persona</th>
        <td>{{ pedidos.persona }}</td>
      </tr>
      <tr>
        <th>Fecha de Entrega</th>
        <td>{{ pedidos.fecha_entrega }}</td>
      </tr>
      <tr>
        <th>Sabor de Pedido</th>
        <td>{{ pedidos.sabor }}</td>
      </tr>
    </table>
    <form method="post">
      {% csrf_token %}
      <input type="submit" value="Delete" class="btn btn-danger">
      <a href="{% url 'Cakes:pedidos_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
 </div
{% endblock content %}

templates/Cakes/pedidos_detail.html
<!DOCTYPE html>
{% include 'Cakes/base.html' %}
{% block content %}
<div class="container mt-5">
    <h1>Model Details</h1>
    <hr>
    <div class="row">
      <div class="col-md-4">
        <p><strong>Persona</strong> {{ pedidos.persona }}</p>
        <p><strong>Sabor</strong> {{ pedidos.sabor }}</p>
        <p><strong>Fecha de Entrega</strong> {{ pedidos.fecha_entrega }}</p>
      </div>
      <div class="col-md-4">
        <p><strong>Detalles</strong> {{ pedidos.detalles}}</p>
        <p><strong>Fecha de Pedido</strong> {{ pedidos.fecha_pedido }}</p>
      </div>
    </div>
    <form method="post" action="{% url 'Cakes:pedidos_delete' object.pk %}">
      {% csrf_token %}
      <a href="{% url 'Cakes:pedidos_update' object.pk %}" class="btn btn-warning mr-2">Update</a>
      <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this object?');" />
      <input type="hidden" name="_method" value="DELETE" />
   </form>
   
</div>
  

  
{% endblock content %}

templates/Cakes/pedidos_form.html
<!DOCTYPE html>
{% include 'Cakes/base.html' %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<div class='container'>
    <h1>Pedido Nuevo</h1>
    {{form.media }}
    <form class='form' method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type='submit' class='btn btn-primary'>Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

templates/Cakes/pedidos_list.html
<!DOCTYPE html>
{% include 'Cakes/base.html' %}
{% block content %}
    <div class='container'>
        <table id="example" class="table" style="width:100%">
            <thead>
                <tr>
                    <th>Persona</th>
                    <th>Fecha De Entrega</th>
                    <th>Direccion</th>
                    <th>Sabor</th>
                    <th>Fecha de pedido</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos_list %}
                <tr class={{pedido.days}}> 
                    <td><a href="{% url 'Cakes:pedidos_detail' pedido.pk %}">{{pedido.persona}}</a></td>
                    <td>{{pedido.fecha_entrega}}</td>
                    <td>{{pedido.direccion}}</td>
                    <td>{{pedido.sabor}}</td>
                    <td>{{pedido.fecha_pedido}}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                </tr>
            </tfoot>
        </table>
    </div>
{% endblock content %}